FROM node:12-alpine
RUN apk update && apk add build-base autoconf automake libtool pkgconfig nasm

WORKDIR '/app'
COPY ./package.json ./
RUN npm install --global gatsby-cli && gatsby telemetry --disable
RUN npm install
COPY . .
CMD ["npm", "run", "start"]