sudo: required
services:
  - docker

language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
  
script: "rake"

before_install:
  - docker build -t mnouaytid/open-profile -f ./client/Dockerfile.dev ./client

after_success:
  - docker build -t mnouaytid/open-profile-client ./client
  - docker build -t mnouaytid/open-profile-nginx ./nginx
  - docker build -t mnouaytid/open-profile-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mnouaytid/open-profile-client
  - docker push mnouaytid/open-profile-nginx
  - docker push mnouaytid/open-profile-server